module.exports = [
    {
        varietal: "Barbera",
        region: "Piedmont",
        shade: "Red",
        description: "Barbera is a juicier, fruitier wine with notes of cherry, raspberry, blueberry, and blackberry. You will also get some hints of baking spice while tasting. High acidity and low tannin. Barbera pairs well with any food; it is a very approachable red.",
        img: "https://i.imgur.com/VTvXK6V.jpg",
    },
    {
        varietal: "Barolo",
        region: "Piedmont",
        shade: "Red",
        description: "This high-tannin red has a ton of flavor, mostly bearing from the oak casks where they are aged. Full-bodied and highly-acidic. Tar and rose aromas on the nose. Flavors of truffle, chocolate, dried fruit, and eucalyptus.",
        img: "https://i.imgur.com/KZ3Nyfm.jpg",
    },
    {
        varietal: "Chianti",
        region: "Tuscany",
        shade: "Red",
        description: "Chianti carries notes of red fruit, fried herbs, balsamic vinegar, smoke, and game. This medium-bodied, dry wine has high tannins and pairs extremely well with any of your favorite pasta dishes.",
        img: "https://i.imgur.com/NeGMhuo.jpg",
    },
    {
        varietal: "Dolcetto",
        region: "Piedmont",
        shade: "Red",
        description: "This red is light and dry, and less on the sweet side. Low-acidity, juicy, and earthy. Dolcetto has a low-tannin and notes of licorice, black cherry, blueberry, blackberry, and prune. Bitter almond finish.",
        img: "https://i.imgur.com/DGXsL9X.jpg",
    },
    {
        varietal: "Montepulciano",
        region: "Abruzzo",
        shade: "Red",
        description: "This medium-bodied red grape wine carries notes of red plum, oregano, sour cherry, boysenberry, and tar. Medium-high tannin and acidity. Montepulciano pairs nicely with rich, savory foods.",
        img: "https://i.imgur.com/SyXjXEM.jpg",
    },
    {
        varietal: "Nebbiolo",
        region: "Piedmont",
        shade: "Red",
        description: "Nebbiolo has notes of rose, cherry, leather, and anise. The floral and light fruit aromas will fool you into thinking this is a lighter-bodied wine. This one is extremely full-bodied, high tannins and highly acidic.",
        img: "https://i.imgur.com/xRLvlx3.jpg",
    },
    {
        varietal: "Nero d'Avola",
        region: "Sicily",
        shade: "Red",
        description: "Full-bodied fruity red with notes of black cherry, prune, black plum, and licorice. Medium-to-high acidity and robust tannins. This red will leave you with a spicy, peppery finish.",
        img: "https://i.imgur.com/mrgpQVw.jpg",
    },
    {
        varietal: "Sangiovese",
        region: "Tuscany",
        shade: "Red",
        description: "Sangioveses carry notes of tart cherry, red plum, strawberry, and fig. Subtle notes of roasted pepper, tobacco, oregano, and dried roses.",
        img: "https://i.imgur.com/neSCRai.jpg",
    },
    {
        varietal: "Falanghina",
        region: "Campania",
        shade: "White",
        description: "Falanghina has notes of bitter orange, orange peel, tangerine, lemon, peach, and candied fruits. Dry with high-acidity. Floral, herbal and tropical fruit flavors. This white wine pairs well with scallops, prawns, or clams.",
        img: "https://i.imgur.com/H8ALHAO.jpg",
    },
    {
        varietal: "Fiano",
        region: "Campania",
        shade: "White",
        description: "This white wine has notes of honeydew, asian pair, hazelnut, orange peel, and pine. Very strong flavor and more full-bodied than most other white wines. Intense floral aromas.",
        img: "https://i.imgur.com/PiND8vZ.png",
    },
    {
        varietal: "Gavi",
        region: "Piedmont",
        shade: "White",
        description: "Gavi is crisp, fresh and lovely. This lightly-bodied white wine has high minerality on the back end and notes of citrus, green apples, and almonds. Pairs nicely with cheese or grilled fish.",
        img: "https://i.imgur.com/vGmEblK.png",
    },
    {
        varietal: "Greco",
        region: "Campania",
        shade: "White",
        description: "Greco's medium-to-full body has notes of spice, herbs and citrus. With relatively high acidity and substantial minerality, this white wine is not on the fruit-forward side. If there were fruit notes, they would be stone fruit, apple, pear, and peach.",
        img: "https://i.imgur.com/eHr35YE.jpg",
    },
    {
        varietal: "Pecorino",
        region: "Abruzzo",
        shade: "White",
        description: "This crisp, aromatic white wine has notes of soft fruit, florals, dry herbs, and minerality. Pecorino has medium acidity and a heavier mouthfeel. This white wine conveniently pairs with pecorino cheese, but also goes well with fish and shellfish.",
        img: "https://i.imgur.com/JSzodil.png",
    },
    {
        varietal: "Prosecco",
        region: "Veneto",
        shade: "White",
        description: "Prosecco is a light-bodied, vibrant, highly-aromatic, crisp sparkling wine. This medium-to-high acidity wine carries notes of apple, honeysuckle, peach, melon and pear. You can sometimes grab a hint of hazelnut and tropical fruit on the backend. Unbeatable mimosa ingredient.",
        img: "https://i.imgur.com/YcqWLX5.png",
    },
    {
        varietal: "Verdicchio",
        region: "Marche",
        shade: "White",
        description: "Verdicchio has noticably high acidity and notes of peach, lemon curd and almond skin. This lightly-bodied white wine is often used as the base of most sparkling wines.",
        img: "https://i.imgur.com/6thH9VH.png",
    },
    {
        varietal: "Vermentino",
        region: "Sardinia",
        shade: "White",
        description: "This white wine is light-bodied but has an unexpectedly complex taste. Vermentino is less on the sweet side, with notes of lime, grapefruit, green apple, almond, and daffodil. These notes give this wine high-acidity. This dry white has a bitter and snappy finish, similar to that of a grapefruit.",
        img: "https://i.imgur.com/K8uFlua.png",
    },
];