module.exports = [
    {
        varietal: "Barbera",
        region: "Piedmont",
        shade: "Red",
        description: "TODO: EDIT DESCRIPTION",
        img: "#",
    },
    {
        varietal: "Barolo",
        region: "Piedmont",
        shade: "Red",
        description: "TODO: EDIT DESCRIPTION",
        img: "#",
    },
    {
        varietal: "Chianti",
        region: "Tuscany",
        shade: "Red",
        description: "TODO: EDIT DESCRIPTION",
        img: "#",
    },
    {
        varietal: "Dolcetto",
        region: "Piedmont",
        shade: "Red",
        description: "TODO: EDIT DESCRIPTION",
        img: "#",
    },
    {
        varietal: "Montepulciano",
        region: "Abruzzo",
        shade: "Red",
        description: "TODO: EDIT DESCRIPTION",
        img: "#",
    },
    {
        varietal: "Nebbiolo",
        region: "Piedmont",
        shade: "Red",
        description: "TODO: EDIT DESCRIPTION",
        img: "#",
    },
    {
        varietal: "Nero d'Avola",
        region: "Sicily",
        shade: "Red",
        description: "TODO: EDIT DESCRIPTION",
        img: "#",
    },
    {
        varietal: "Sangiovese",
        region: "Tuscany",
        shade: "Red",
        description: "TODO: EDIT DESCRIPTION",
        img: "#",
    },
    {
        varietal: "Falanghina",
        region: "Campania",
        shade: "White",
        description: "TODO: EDIT DESCRIPTION",
        img: "#",
    },
    {
        varietal: "Fiano",
        region: "Campania",
        shade: "White",
        description: "TODO: EDIT DESCRIPTION",
        img: "#",
    },
    {
        varietal: "Gavi",
        region: "Piedmont",
        shade: "White",
        description: "TODO: EDIT DESCRIPTION",
        img: "#",
    },
    {
        varietal: "Greco",
        region: "Campania",
        shade: "White",
        description: "TODO: EDIT DESCRIPTION",
        img: "#",
    },
    {
        varietal: "Pecorino",
        region: "Abruzzo",
        shade: "White",
        description: "TODO: EDIT DESCRIPTION",
        img: "#",
    },
    {
        varietal: "Prosecco",
        region: "Veneto",
        shade: "White",
        description: "TODO: EDIT DESCRIPTION",
        img: "#",
    },
    {
        varietal: "Verdicchio",
        region: "Marche",
        shade: "White",
        description: "TODO: EDIT DESCRIPTION",
        img: "#",
    },
    {
        varietal: "Vermentino",
        region: "Sardinia",
        shade: "White",
        description: "TODO: EDIT DESCRIPTION",
        img: "#",
    },
];